### PR TITLE
Update rpi-os.md

### PR DESCRIPTION
**Pull request by amo7een**
I used Microsoft Style Guide and Google Developer Documentation Style Guide to verify any changes that went beyond basic grammar, punctuation, and spelling. Let me know if this is helpful.

### CODE REVIEW

**Comment by s-matyukevich** [comment]
Thanks @amo7een ! This indeed is very helpful. Merging the PR now.

**Comment by amo7een** [comment]
Great! It’s helpful for me, too. I can learn a lot. I’ll take a look at more of the docs.

**Comment by s-matyukevich** [comment]
@amo7een  Actually, the lesson that you checked was already verified by other guys and all basic grammar mistakes were already fixed. Most of the other lessons most likely still contain a lot of basic grammar mistakes and typos. Fixes for such kind of mistakes if the top priority for the project right now. Compliance with the style guides is very cool, but it is the second priority, so if it takes too much time to verify such compliance you can simply skip it for now - I will accept you PRs anyway. 
Thanks once again for your help!

**Comment by amo7een** [comment]
OK, cool. I will take a look.

**Pull request merged**
