### PR TITLE
Adding exercise answer 1.2

### PR DESCRIPTION
**Pull request by xdfm1**

### CODE REVIEW

**Comment by s-matyukevich** [comment]
Perfect, good job!

**Comment by bl4ckout31** [comment]
@xdfm1 How did you get the UART reference clock ? I spent my weekend reading documentations and the linux git tree and all I could find was the 3 MHz set by Raspbian which of course didn't help very much.

**Comment by s-matyukevich** [comment]
@bl4ckout31  I guess init_uart_clock property default value is what you need https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md The value is 48MHz

**Comment by s-matyukevich** [comment]
@xdfm1 do you have Twitter account? I want to tell the community about your contributions

**Comment by bl4ckout31** [comment]
I feel so dumb right now, thank you anyway.

**Comment by xdfm1** [comment]
@bl4ckout31 just saw your question which has been answered by Sergey.
@s-matyukevich I don't have a twitter account associated with this handle. I like the detailed style of this course, please keep up the good work.

**Pull request merged**
